name: simple_list_extensions
description: Contains some useful list methods.
version: 1.0.0
repository: https://github.com/komakurae/simple_list_extensions

environment:
  sdk: ^3.4.1

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
