name: Test package

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
      - .github/**
  pull_request:


jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: 'stable'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Run the tests
      - name: Run tests
        run: flutter test